[package]
name = "sn-trie-proofs"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet-types-core = { version = "0.1.0", default-features = false, features = [
    "serde",
    "hash",
] }
bitvec = "1.0.1"
anyhow = "1.0.75"
