# See: https://rust-lang.github.io/rustfmt
max_width = 140
use_field_init_shorthand = true

# Unstable
# comment_width = 140
# condense_wildcard_suffixes = true
# format_code_in_doc_comments = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# normalize_comments = true
# unstable_features = true
# wrap_comments = true